D: 2
L_ft: 1
avg: False
beta: 8
beta1: 0.9
beta2: 0.99
dt: 0.1
gamma: 1
lam: 1
lam1: 0.7
lam_m: 0.8
maxiter: 100
model: 1
momentum: false
nump: 256
proj: false
rep: 1
sigma: 0.1
sim: 1
simname: 250612Exp_2