D: 15
L_ft: 1
avg: True
beta: 100
beta1: 0.9
beta2: 0.99
dt: 0.1
gamma: 1
lam: 1
lam1: 0
lam_m: 0.8
maxiter: 1000
model: 1
momentum: false
nump: 50
proj: false
rep: 1
sigma: 3
sim: 50
noise_type : homo
simname: 250612Exp_2